### ISSUE TITLE
Default browser handling

### ISSUE THREAD

**Issue by Therzok** [pwnwriter/rayso#1]
There are alternatives to browser handling that could improve quality of life for users, like:

1. Reading the `BROWSER` env var
2. Using `x-www-browser` if it exists on `PATH`
3. `xdg` to query the default browser from the OS via the `default-web-browser` property.
4. [webbrowser](https://docs.rs/webbrowser/latest/webbrowser/) or [open](https://docs.rs/open/latest/open/) crate?

**Comment by pwnwriter** [comment]
oh yeah, i just changed to `xdg-open` instead of direct `browser-binary`. Thanks for pointing that out :)
